// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMJOjTR4fW2-PFmMD5dkYBxwGCDBJHw_0',
    appId: '1:121548389217:web:182bab79e49d3d83a4e320',
    messagingSenderId: '121548389217',
    projectId: 'fir-test1-18725',
    authDomain: 'fir-test1-18725.firebaseapp.com',
    storageBucket: 'fir-test1-18725.appspot.com',
    measurementId: 'G-H7408QT4X1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuEWJAG2RT3YU7ewY3_XRaMZ3oVpeaFSU',
    appId: '1:121548389217:android:bfed8d9716597d2da4e320',
    messagingSenderId: '121548389217',
    projectId: 'fir-test1-18725',
    storageBucket: 'fir-test1-18725.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZNN1NNAyLPerxsANrNwcksuthytxdau8',
    appId: '1:121548389217:ios:5d6685abb145fcf0a4e320',
    messagingSenderId: '121548389217',
    projectId: 'fir-test1-18725',
    storageBucket: 'fir-test1-18725.appspot.com',
    iosClientId: '121548389217-7mg1vufts2pontvgh1mhi1kmeajqio6a.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZNN1NNAyLPerxsANrNwcksuthytxdau8',
    appId: '1:121548389217:ios:5d6685abb145fcf0a4e320',
    messagingSenderId: '121548389217',
    projectId: 'fir-test1-18725',
    storageBucket: 'fir-test1-18725.appspot.com',
    iosClientId: '121548389217-7mg1vufts2pontvgh1mhi1kmeajqio6a.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest1',
  );
}
